### ISSUE TITLE
Does not compile without minor edits

### ISSUE THREAD

**Issue by wilsonsamm** [kristianlm/small-lisp#1]
I'm using GCC 5.4.0, and I found I get

    sl3.c:(.text+0xbf9): undefined reference to `car'
    sl3.c:(.text+0xc14): undefined reference to `cdr'

unless I remove the inline keyword from the car and cdr functions. 
This is when I do simply gcc sl3.c at the command prompt. Am I doing something wrong, or do I need to enable a particular compiler option or something?

**Comment by kristianlm** [comment]
Hi @wilsonsamm, and thanks for trying this out. I haven't looked at this for a couple of years. It seems that `inline` behaves differently on different GCC versions. So no, you didn't miss anything.

https://stackoverflow.com/questions/19068705/undefined-reference-when-calling-inline-function

I made a commit where the `inline` keywords are ignored. The compiler knows best whether to inline of not. Should be working now!
